http://localhost:3000

###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "no@test.com",
  "password": "password123"
}

###
# @name login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "no@test.com",
  "password": "password123"
}

###
GET http://localhost:3000/api/auth/protected/me
Cookie: {{login.response.headers.Set-Cookie}}